### ISSUE TITLE
provider Striper Checkout Session (with SCA support) does not appear in the dropdown

### ISSUE THREAD

**Issue by seriousTom** [FLUX-SE/SyliusPayumStripePlugin#11]
Hello,
I have installed this package but payment method 'Striper Checkout Session (with SCA support) ' does not in the dropdown in admin section. I only see Stripe checkout (no SCA support).
https://gyazo.com/94cde064ec277d4675c6c9df7ce0c0d0

**Comment by Prometee** [comment]
Hello @seriousTom,

Are you sure you instantiated the plugin  as you can see it here :
https://github.com/FLUX-SE/SyliusPayumStripePlugin#installation ?

**Comment by seriousTom** [comment]
Oh... When the installation was finished in the config/bundles.php appeared this line `FluxSE\PayumStripeBundle\FluxSEPayumStripeBundle::class => ['all' => true],` so I thought it was the correct one. Now I see it is different than specified in the documentation.

**Comment by Prometee** [comment]
In fact the required bundle is auto installed but all Sylius Plugin are not suffixed by "Bundle" so this Sylius plugin is not installed automatically into `config/bundle.php`.
