### ISSUE TITLE
No option to create a payment method for Stripe with SCA support in Sylius

### ISSUE THREAD

**Issue by siven-xtn** [FLUX-SE/SyliusPayumStripePlugin#12]
Hello, 

I have tried to install your Sylius Stripe plugin on an existing Sylius 1.5.1.The installation was successful.However, I do not see the option to choose ‘Stripe Checkout Session (with SCA support) when I click on the ‘Create’ button.

I have also tried to add the plugin on a fresh installation of Sylius 1.8.1 and I still have the same issue.

Do I need to a configuration for payum so that it recognises the relevant factory?

Hopefully, you can easily identify the issue I am facing.

Kind regards,
Siven

**Comment by Prometee** [comment]
Hi Siven,

If you don't see the option it's because the plugin is not installed, can you check the installation steps : https://github.com/FLUX-SE/SyliusPayumStripePlugin#installation ?

**Comment by siven-xtn** [comment]
Hi,

Thank you very much for your reply.

Actually, the #11  issue provided me with the clue to fix it. The installation was not complete, as you pointed out. The entry added by the recipe in the bundles.php file is not the same as the one required for installation.

Is it possible to add the required line as part of the flex recipe? If yes, I would like to contribute to the project to do this as a way to Thank You.

Thank you again for your help.

**Comment by Prometee** [comment]
I have to do it 😊 I know, I will take some time next week to do it 😉

**Comment by Prometee** [comment]
@siven-xtn pull request done and waiting for validation : https://github.com/symfony/recipes-contrib/pull/1023
