### ISSUE TITLE
Unable to change payment method, or back of out payment and then pay

### ISSUE THREAD

**Issue by mbklnd** [FLUX-SE/SyliusPayumStripePlugin#18]
I have been having issues while trying to configure this plugin on an existing 1.8 project, so thought I'd give it a try with a fresh install of Sylius to see if the issue is a project issue or global issue.

This issue may be linked to https://github.com/FLUX-SE/SyliusPayumStripePlugin/issues/2 however, I cannot see the actual commit in the commit history which fixes that issue as it's not linked, so I cannot be sure.

**Steps to reproduce:**
1. Install fresh Sylius (1.9.1) with demo products (en_GB, GBP config)
2. Install FLUX-SE/SyliusPayumStripePlugin via composter (1.2.3)
3. Config Stripe for local development with test keys
4. Add product to basket
5. Continue through checkout
6. Enter Stripe checkout from Confirmation page
7. Go back to store via 'back to store' button in top left.
8. From order summary page, attempt to pay via Stripe (this plugin's SCA version of Stripe)
9. Page reloads ,and displays **There was an unknown problem with payment.** flash message

![image](https://user-images.githubusercontent.com/18394700/111770243-11d23380-88a2-11eb-90ad-fa0fe0ccfa42.png)

I have attempted to look through the logs, and profiler, but there doesn't seem to be any obvious indication of what is going wrong here and I'm not very familiar with the inner workings of Payum.

Hopefully this issue is explained clearly enough.

**Comment by Prometee** [comment]
Hello @mbklnd,

Can you tell me what is the version installed of `flux-se/payum-stripe` :

```shell
composer show flux-se/payum-stripe
```

If it's a version >= 2.0.0 then to fix this issue require this :

```shell
composer require "flux-se/payum-stripe:<2.0"
```

**Comment by mbklnd** [comment]
Hi @Prometee - Thanks for picking this one up so fast.

```
composer show 
outputs: versions: * v1.2.3
```

details from the failing payment in `sylius_payment` database table, outputs:

```
{"id":"pi_1IWforI7hIMki8gOWc9atiGC","object":"payment_intent","allowed_source_types":["card"],"amount":4203,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_1IWforI7hIMki8gOWc9atiGC"},"client_secret":"pi_1IWforI7hIMki8gOWc9atiGC_secret_T8CHj0S60rkvFLsB0eGw3fJDC","confirmation_method":"automatic","created":1616150681,"currency":"gbp","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"6m9hzvb9Lv9annOcbsLlom0RA88gszBCBa2TT590IV8"},"next_action":null,"next_source_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_source","transfer_data":null,"transfer_group":null}
```

**Comment by Prometee** [comment]
@mbklnd 

ah ! `status = require_source` seems to be a new status, this is why `FluxSE\PayumStripe\Action\StatusAction` is not able to know the `status` of the payment.

I'll check it this afternoon, but it's weird because this status is not yet listed in the `stripe/stripe-php` : https://github.com/stripe/stripe-php/blob/master/lib/PaymentIntent.php#L69-L72

**Comment by mbklnd** [comment]
Ah... Nice spot.

Could it be that I'm using an old/incorrect version of the Stripe API?

**Comment by Prometee** [comment]
@marieflux ok I found why : https://stripe.com/docs/payments/intents#intent-statuses :
> Versions of the API before 2019-02-11 show requires_source instead of requires_payment_method and requires_source_action instead of requires_action.

I'm checking how to do it

**Comment by mbklnd** [comment]
It's probably time to update the Stripe API version we are using for this project anyway.

**Comment by Prometee** [comment]
I agree, but I will try to found a way to warn about this somewhere.

**Comment by mbklnd** [comment]
Yeah, a note on the required version of the Stripe API would be great.

Thanks for your help troubleshooting this

**Comment by Prometee** [comment]
I will require it on `flux-se/payum-stripe` directly, the error will be displayed by composer directly 😉

**Comment by mbklnd** [comment]
I had version `v7.75.0` installed, and can confirm this is working.
