### ISSUE TITLE
Stripe dashboard message

### ISSUE THREAD

**Issue by KrOv3an** [FLUX-SE/SyliusPayumStripePlugin#20]
I have integrated the SCA support plugin for our shop, but this message still appears at Stripe Dashboard.
"Important: Update your integration for SCA
While European regulation mandates that full enforcement of Strong Customer Authentication (SCA) begins on Dec 31, 2020, some banks are now declining a portion of payments that aren't SCA-ready. To make sure your payments are approved, please update your integration."
Maybe it's a Stripe issue and it disappears in some time?

**Comment by Prometee** [comment]
Hello @KrOv3an,

Normally, after 7 consecutive days of using the SCA process Stripe will make this message disappear. If not fill free to contact the Stripe support. On my own account it disappears a while ago, but I didn't notice exactly when it did.

**Comment by KrOv3an** [comment]
Thank you for your help and time :) Have a nice day!

**Comment by KrOv3an** [comment]
> Hello @KrOv3an,
> 
> Normally, after 7 consecutive days of using the SCA process Stripe will make this message disappear. If not fill free to contact the Stripe support. On my own account it disappears a while ago, but I didn't notice exactly when it did.

Thank you for your help and time :) Have a nice day!

**Comment by Prometee** [comment]
@KrOv3an thanks 😉, have a nice day too !
