### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by xchopin** [FLUX-SE/SyliusPayumStripePlugin#22]
Hi,

Are there any ways to automate the refund of orders?

For example if I refund an order that uses this Stripe gateway it only shows the refund on Sylius, it is not actually sent to my Stripe account so I have to manually refund the person, is that a normal scenario?

thank you

**Comment by Prometee** [comment]
Hi @xchopin,

I'm planning to add it very soon to release the v2.0.0. The refund ability is already available in the main library : https://github.com/FLUX-SE/PayumStripe/blob/master/src/Action/RefundAction.php
It should be easy to add it on Sylius with a winzou state machine callback like other gateways are already doing it.

**Comment by xchopin** [comment]
Awesome thank you
