### ISSUE TITLE
Error on missing dependencies when installing the bundle

### ISSUE THREAD

**Issue by johnkrovitch** [FLUX-SE/SyliusPayumStripePlugin#24]
Hi,

I have several errors when installing the plugin on a Sylius 1.9 :

with ^1.2 :  Unable to find file "@FluxSESyliusPayumStripePlugin/Resources/config/config.yaml".  
with ^2.0 : The service "flux_se.sylius_payum_stripe.extension.update_payment_state" ha  
!!    s a dependency on a non-existent service "payum.storage.sylius_component_co  
!!    re_model_payment".      

I try to figure what is not working.

**Comment by Prometee** [comment]
Hi @johnkrovitch,

I guess you make a `composer req flux-se/sylius-payum-stripe-plugin` first which is installing the last version (`v2.0`) and then you manually change the version into your `composer.json` file to downgrade it.
Installing the last version first is executing the symfony recipe, but it won't overwrite it when you downgrade a package, that's why you get the error message : `Unable to find file "@FluxSESyliusPayumStripePlugin/Resources/config/config.yaml".`.
You can execute this command to reinstall the recipe :
```bash
composer fix-recipes flux-se/sylius-payum-stripe-plugin --force
```

About the second error : `payum.storage.sylius_component_core_model_payment`, can you print here the result of this command ?

```bash
./bin/console debug:container payum.storage.sylius_component_core_model_payment
```

**Comment by johnkrovitch** [comment]
Hi @Prometee,
thanks for your response. Sorry for the false positive for version 1.2, the configuration file from recipe was not deleted.

About the error on v2.0, the command "./bin/console debug:container payum.storage.sylius_component_core_model_payment" give the same results as the can not be build because of the error :

`
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                                                                                                                            
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                                
  The service "flux_se.sylius_payum_stripe.extension.update_payment_state" has a dependency on a non-existent service "payum.storage.sylius_component_core_model_payment".  
                                                                                                                                                                            

Exception trace:
  at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
 Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
 Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:90
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
 Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
 Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:40
 Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process() at /home/docker/www/app/vendor/symfony/dependency-injection/Compiler/Compiler.php:91
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /home/docker/www/app/vendor/symfony/dependency-injection/ContainerBuilder.php:736
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /home/docker/www/app/vendor/symfony/http-kernel/Kernel.php:541
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /home/docker/www/app/vendor/symfony/http-kernel/Kernel.php:780
 Symfony\Component\HttpKernel\Kernel->preBoot() at /home/docker/www/app/vendor/symfony/http-kernel/Kernel.php:121
 Symfony\Component\HttpKernel\Kernel->boot() at /home/docker/www/app/vendor/symfony/framework-bundle/Console/Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /home/docker/www/app/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/docker/www/app/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /home/docker/www/app/bin/console:38
`
I think this stack trace is not very useful.....
I am on docker with docker-compose, php 7.4 fpm and caddy server.

I try to look where this service should be defined.

**Comment by johnkrovitch** [comment]
In the service definition, it seems to work if replace :

`
  flux_se.sylius_payum_stripe.extension.update_payment_state:
    public: true
    class: FluxSE\SyliusPayumStripePlugin\Extension\UpdatePaymentStateExtension
    arguments:
      $factory: '@sm.factory'
      $storage: '@payum.storage.sylius_component_core_model_payment'
      $getStatusRequestFactory: '@sylius.factory.payum_get_status_action'
    tags:
      - name: payum.extension
        factory: stripe_checkout_session
        alias: flux_se.sylius_payum_stripe.extension.update_payment_state
`
by

`
  flux_se.sylius_payum_stripe.extension.update_payment_state:
    public: true
    class: FluxSE\SyliusPayumStripePlugin\Extension\UpdatePaymentStateExtension
    arguments:
      $factory: '@sm.factory'
      $storage: '@payum.security.token_storage'
      $getStatusRequestFactory: '@sylius.factory.payum_get_status_action'
    tags:
      - name: payum.extension
        factory: stripe_checkout_session
        alias: flux_se.sylius_payum_stripe.extension.update_payment_state
`

I change "**$storage: '@payum.storage.sylius_component_core_model_payment'**" by "**$storage: '@payum.security.token_storage'**"

**Comment by Prometee** [comment]
I get it !
In my own project and test environment I don't have any entities extending the base `Sylius\Core\Entity\*`.

You are using the default sylius installation and it's using by default an overrides of the `Payment` entity, this override will change the value of the parameter `%sylius.model.payment.class%` changing the name of the service to `payum.storage.app_entity_payment_payment`.

I will make a new release quickly to fix this. Meanwhile you can use `payum.storage.app_entity_payment_payment`.

**Comment by johnkrovitch** [comment]
Yes ! That's it ! Indeed when i run "bin/console debug:container | grep payum.storage", I have only :
```bash
"payum.storage.app_entity_order_order"
"payum.storage.app_entity_payment_payment"
```

Thank you very much !

**Comment by Prometee** [comment]
@johnkrovitch thank you for spotting this bug, I released a new version, you can try it 😉
