### ISSUE TITLE
No payment form

### ISSUE THREAD

**Issue by Healkiss** [FLUX-SE/SyliusPayumStripePlugin#28]
Hi !
Thank you for your work, i'm trying to install a stripe payment to my fresh project
`        "php": "^7.4 || ^8.0",
        "flux-se/payum-stripe-bundle": "^2.0",
        "flux-se/sylius-payum-stripe-plugin": "^2.0",
        "php-http/guzzle6-adapter": "^2.0",
        "sylius/payum-bundle": "^1.10",
        "sylius/sylius": "^1.10",
        "symfony/dotenv": "^4.4 || ^5.2",
        "symfony/flex": "^1.11",
        "synolia/sylius-mail-tester-plugin": "^2.1"
`
I succeded to install it and put well keys and webook (if when we test from stripe, a 302 response is the waited response)

But in the payment funnel, the order is placed without asking payment from user.

I can found the order 'waiting for payment' on the backend.

Is there anything to add after the installation process ? Or miss I something ?

Thanks for your help.

**Comment by Prometee** [comment]
Hello @Healkiss,

You seems to not being familiar with Sylius checkout. During the checkout you are choosing the payment method and then when you reach the checkout complete page, there is a button at the end of the page which lead you to Stripe portal to pay the order.

**Comment by Healkiss** [comment]
Indeed, i'm diving again in S
ylius, but it's seems to me that I didn't get those kind of behaviour previously.
I don't see any button than lead me a such page. The blue button only validate the command and that's all
![commander](https://user-images.githubusercontent.com/1389874/129193355-35086859-4adf-4d10-ba8b-611a38fd45ba.png)

**Comment by Prometee** [comment]
@Healkiss Essayez de cliquer sur le bouton bleu "Commander" 😉

**Comment by Healkiss** [comment]
Le problème c'est que j'ai bien les requêtes 'pay', 'complete' qui partent et se redirigent en 302 jusqu’à la page d'accueil. Aucun paiement n'est demandé. Je n'ai pas d'erreur dans les logs. Etant sur un installation neuve avec seulement ce plugin, je me demande si j'ai pas loupé qqch dans la config ..

**Comment by Prometee** [comment]
L'installation par défaut de Sylius accepte déjà ces routes, vous avez donc une installation custom.
En mode dev le plugin ne fait pas d'action particulières, le fait que la commande soit en status "En attente de paiement" est normal vu que le portail Stripe n'a pas encore été affiché au visiteur et c'est ce qui explique pourquoi vous n'avez aucun log dans Stripe.

Une fois que le bouton "Commander" a été cliqué la route utilisé est :
`sylius_shop_order_pay` qui effectuera une redirection vers la route: `payum_capture_do `.

Il y aura aussi une route pour le retour à partir du portail Stripe vers le shop : `sylius_shop_order_after_pay`
et une notification par webhook utilisant la route `payum_notify_do`

**Comment by Healkiss** [comment]
Y'a t'il un bundle complementaire `payum` à installer ? Car il n'y a encore rien de custom (mis a part mes 2 produits et le 'livraison Calculator' perso)

**Comment by Prometee** [comment]
L'application de test fait exactement ce que vous cherchez à faire : https://github.com/FLUX-SE/SyliusPayumStripePlugin/tree/master/tests/Application
Si vous avez juste installé Sylius en suivant la documentation et suivi la documentation d'installation de ce plugin, il n'y a rien de plus à faire. Toutes les dépendances sont gérés par composer vous n'avez donc pas à installer quoi que ce soit de plus.

**Comment by Healkiss** [comment]
Merci beaucoup pour votre temps (et votre rapidité de réponse). Je risque de le réinstaller une fois de plus. Vous m'avez éclairez tout de même sur la processus de paiement.
Bonne journée !

**Comment by Prometee** [comment]
Merci à vous 😉

Vous pouvez aussi lire les autres issues fermées ou ouvertes disponible dans ce repository. J'ai essayé d'être le plus détaillé possible concernant le fonctionnement de `Payum` et de `Sylius` dans certaine d'entre elles.

**Comment by Healkiss** [comment]
Pour information, en Sylius 1.9 et 1.10, l'install composer demande qq ajustements. Au mois un `--with-all--dependencies` après avoir supprimé le `"stripe/stripe-php": "^6.43",` qui est dans le composer de Sylius

**Comment by Prometee** [comment]
Il faut en effet supprimer cette dépendance, elle est nécessaire que si vous voulez utiliser la gateway Stripe comprise dans le package `payum/stripe` qui est très très très vieille désormais. Je vais rajouter cela à la documentation d'installation.

Merci 😉

**Comment by florianthomi** [comment]
Bonjour @Prometee,

avez-vous pu mettre à jour la procédure d'installation, je tente d'installer ce plugin sur Sylius 1.10 mais je rencontre également ce souci de dépendance avec `"stripe/stripe-php": "^6.43"`

**Comment by Prometee** [comment]
Bonjour @florianthomi, mon attention a dut s'égarer ce jour là, je ne l'ai pas mise à jour. Cependant vous pouvez créer une PR afin d'ajouter cette note d'installation au fichier `README.md` cela m'aiderait beaucoup 😉

**Comment by florianthomi** [comment]
Justement je ne vois pas comment résoudre ce conflit, j'aurais espéré une marche à suivre dans la doc...

**Comment by Healkiss** [comment]
Rien ne vous empêche de supprimer la dépendance Stripe dans cotre composer (celui que vous avez tiré depuis Sylius la première fois). C'est maintenant votre projet.
Puis pour être sur que le plugin SyliusPayumStripePlugin prennent bien stripe, vous pouvez faire un composer install/update --with-all--dependencies

**Comment by Prometee** [comment]
@Healkiss 
Peut être qu'un `conflict` devrait être rajouté au `composer.json` mais il se peut que les dev débutant ne comprennent pas pourquoi le package refuse de s'installer.

**Comment by florianthomi** [comment]
> Rien ne vous empêche de supprimer la dépendance Stripe dans votre composer (celui que vous avez tiré depuis Sylius la première fois). C'est maintenant votre projet. Puis pour être sur que le plugin SyliusPayumStripePlugin prennent bien stripe, vous pouvez faire un composer install/update --with-all--dependencies

@Healkiss 
Mais cette dépendance se trouve dans le core de sylius installé via composer, la modification sera perdue à chaque installation/mise à jour. A moins que je passe à côté de qqch...

**Comment by Prometee** [comment]
@florianthomi c'est une [`require-dev` ](https://github.com/Sylius/Sylius/blob/master/composer.json#L197)dans `sylius/sylius`, par contre ce que vous devez supprimer c'est le [`require-dev`](https://github.com/Sylius/Sylius-standard/blob/master/composer.json#L56) présent dans votre projet Sylius qui est généré à partir de `sylius/sylius-Standard`.

**Comment by florianthomi** [comment]
@Prometee Je l'avais pas vu celui-là ! Merci beaucoup, problème résolu :+1:

**Comment by Prometee** [comment]
Je viens de rajouter la ligne dans le `README.md` :

```shell
composer remove --dev stripe/stripe-php --no-update --no-scripts --no-interaction
composer require flux-se/sylius-payum-stripe-plugin
```
