### ISSUE TITLE
Redirected to homepage instead of Stripe

### ISSUE THREAD

**Issue by Dekminoz** [FLUX-SE/SyliusPayumStripePlugin#30]
Hi,

I've a multi channel Store (one for Canada, one for USA), i've two stripe account each with it's own company . I've created two Stripe checkout session paiement method each with it's own configuration 

My Canada paiement works fine but my USA paiement redirect me to the homepage when i click on "Place order" instead of Stripe and my order status is now "Awaiting paiement"

Can you help me with that ? Thanks

**Comment by Prometee** [comment]
Hello @Dekminoz,

Do you add also the required webhooks for both payment methods ?
Are you using the version 2.* of this plugin ?

**Comment by Prometee** [comment]
Edit : do you setup channels with two different hosts or do you make your own ChannelContext ?
Can you check the Symfony profiler from the checkout summary to the redirection to the homepage ?

**Comment by Dekminoz** [comment]
Hi sorry for my response delay and thank you

> Hello @Dekminoz,
> 
> Do you add also the required webhooks for both payment methods ? Are you using the version 2.* of this plugin ?

Yes, i've updated the plugin to "^2.0" 
I've setup both webhook and API key for canada and US but Stripe don't raise any error , so i think my usshop never go to stripe but failed before.


> Edit : do you setup channels with two different hosts or do you make your own ChannelContext ? Can you check the Symfony profiler from the checkout summary to the redirection to the homepage ?

Yes i have 2 different hosts (shop.domain.com for Canada and usshop.domain.com for USA) in two different channel (nothing custom just the standard Sylius thing)

I'm redirected form payum_capture_do . What information do you need ?

Thx

**Comment by Prometee** [comment]
@Dekminoz I suspect something not working on your US Stripe account.
Here are more questions (sorry)...

Do you set only one channel to each payment gateways ?
Are you using the Stripe **test** publishable and secret key ?
Do you see any logs here https://dashboard.stripe.com/test/logs with request to `GET /v1/checkout/sessions/...` ?

**Comment by Dekminoz** [comment]
I've only one channel active for my paiements method (and it's ok in my basket)
I'm using the production key (i'm on my live environment) publishable and secret

No logs for "/v1/checkout/sessions/" on my logs (i have read the live logs because ,i'm not on the dev env).

**Comment by Dekminoz** [comment]
Hi i've put some debug in your code and, i'm redirected at this point in 

"vendor/payum/payum-bundle/Controller/CaptureController.php: line 39

$token = $this->getPayum()->getHttpRequestVerifier()->verify($request);

i guess my token failed the verification and i'm redirected , do you know why ?

**Comment by Dekminoz** [comment]
Ok so i've found the problem ! It's Payum ! I have my locale in my URL so /en_US/payement is my url and Payum try to go to /payement without my locale... I have to put the following coe in my routes.yaml and it's ok now thank you.

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

**Comment by Prometee** [comment]
Sorry I wasn't able to answer to you since now...

Do you set the sub domain into each channels, also can you check that's generated URLs contain the right sub domain ?

If you use `/{_locale}` to separate the 2 channels then Sylius won't be able to get the right `ChannelContext`. I will recheck how Sylius/Payum is generating those URLs but apparently the `ChannelContext` is not returning the right channel because the default one is returned (it return by default the first channel)
