### ISSUE TITLE
Synced object must have an "object" attribute when cancelling payment

### ISSUE THREAD

**Issue by Loocos** [FLUX-SE/SyliusPayumStripePlugin#34]
Hi there,

I recently updated to the latest version and I'm getting this error after anyone cancel a payment from the Stripe checkout page.

The problem will not be seen by the user but will only appear in the logs file.
Do you have this too ?

Thank you :)

Stacktrace :
![image](https://user-images.githubusercontent.com/26056280/153377628-7f29a796-b706-4390-9144-25572d882bad.png)

**Comment by Prometee** [comment]
Hello @Loocos,

According to the line throwing this Exception, you are using the 1.2 version of this plugin.
You must update to the 2.0 and configure the new Webhook events and avoid other issues.

**Comment by Prometee** [comment]
@Loocos I just get to the same line the error was : https://github.com/FLUX-SE/PayumStripe/blob/master/src/Action/SyncAction.php#L45 you will see it's not throwing an exception on this line, but if you change to a 1.2 tag you will have it : https://github.com/FLUX-SE/PayumStripe/blob/f2437270389d9772c5398865f64b0ea274eebee6/src/Action/SyncAction.php#L45

**Comment by Loocos** [comment]
@Prometee Alright, but I'm using this plugin/package : https://github.com/FLUX-SE/SyliusPayumStripePlugin
I'm not controlling this version at all. And when I tap : composer show 

I can see the good versions used  (local & prod env) : 
flux-se/payum-stripe                            v2.0.3             Payum Stripe gateways
flux-se/payum-stripe-bundle                     v2.0.0             Payum Stripe gateways bundle
flux-se/sylius-payum-stripe-plugin              v2.0.5             Payum Stripe gateways plugin for Sylius.

I'm wondering how can I update to a version than i'm already using haha

Thanks for your help

**Comment by Prometee** [comment]
Alright @Loocos my bad you are using the 2.0 version. This error message can only happens if the payment details contains data coming from provider outside of Stripe API, maybe you have other payment methods and the customer has changed from one payment method to another. See if you can access the payment details triggering the error to verify if I'm right.

**Comment by Loocos** [comment]
Hmm there's only one payment which is Stripe. Like I told you in my first message.
It's only happenning when we click on the back button from the Stripe checkout page.

So i've checked the webhook events and I can see :
- The first one is throwing the error
- The second one (is a retry) and works fine
![image](https://user-images.githubusercontent.com/26056280/153455658-c7ce1fd9-a54c-4a6e-82ab-bf524157f991.png)

You want me to check payment details from Stripe or Sylius ?

**Comment by Prometee** [comment]
From Sylius, because it should be a Stripe PaymentIntent formated in JSON. If it's something else then there is something wrong happening

**Comment by Loocos** [comment]
After multiple test, I'm not able to reproduce it in local/test mode.
Could the API version used can play on this bug ?

> {"id":"pi_3KTNzkDgVX1eRHhK13lIiItR","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KTNzkDgVX1eRHhK13lIiItR"},"client_secret":"pi_3KTNzkDgVX1eRHhK13lIiItR_secret_4HgypPHwqYHtpCme2wwbGdNK8","confirmation_method":"automatic","created":1644919852,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"5e3cMFBj2xlPFKLp6BYSAKI6zxLQlmrhSfSuqKcEuoo"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}

> {"id":"cs_test_a1vsYZUe0eNSNA3ZgVRqmiQFBJzny8kpj1l5tbI3vv8VzDXfMrK9wM5jST","object":"checkout.session","after_expiration":null,"allow_promotion_codes":null,"amount_subtotal":990,"amount_total":990,"automatic_tax":{"enabled":false,"status":null},"billing_address_collection":null,"cancel_url":"https:\/\/127.0.0.1:8000\/order\/after-pay?payum_token=1kLBMxz7yuP37MRLyG-bRgbU-ll33ipo7sE6TQJ8zbA","client_reference_id":null,"consent":null,"consent_collection":null,"currency":"eur","customer":null,"customer_creation":"always","customer_details":{"email":"florent.duthoit@gmail.com","phone":null,"tax_exempt":"none","tax_ids":null},"customer_email":"florent.duthoit@gmail.com","display_items":[{"object":"checkout.session.custom_display_item","amount":990,"currency":"eur","custom":{"description":null,"images":["https:\/\/127.0.0.1:8000\/media\/cache\/resolve\/sylius_shop_product_thumbnail\/1a\/04\/1619203771d05f903bb3a7a537db.jpeg"],"name":"1x - Manchon pour prot\u00e8ge-tibias | XS | Noir"},"quantity":1,"type":"custom"}],"expires_at":1645006426,"livemode":false,"locale":null,"metadata":{"token_hash":"Hr8BlZNQzCa3_EUs2W8-SDB4wycRkhjH2_mpvkNKG7A"},"mode":"payment","payment_intent":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6","payment_link":null,"payment_method_options":[],"payment_method_types":["card"],"payment_status":"unpaid","phone_number_collection":{"enabled":false},"recovered_from":null,"setup_intent":null,"shipping":null,"shipping_address_collection":null,"shipping_options":[],"shipping_rate":null,"status":"open","submit_type":null,"subscription":null,"success_url":"https:\/\/127.0.0.1:8000\/order\/after-pay?payum_token=1kLBMxz7yuP37MRLyG-bRgbU-ll33ipo7sE6TQJ8zbA","total_details":{"amount_discount":0,"amount_shipping":0,"amount_tax":0},"url":"https:\/\/checkout.stripe.com\/pay\/cs_test_a1vsYZUe0eNSNA3ZgVRqmiQFBJzny8kpj1l5tbI3vv8VzDXfMrK9wM5jST#fidkdWxOYHwnPyd1blpxYHZxWndQZklcd1E8b0cwMkJycExHXTFAfHc1STU1cFZJaFE0UlAnKSdjd2poVmB3c2B3Jz9xd3BgKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSdga2RnaWBVaWRmYG1qaWFgd3YnP3F3cGB4JSUl"}


> {"id":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KTO2YDgVX1eRHhK3ZfdUdU6"},"client_secret":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6_secret_FFyJR50pcJHNf5H26hfzdfyOz","confirmation_method":"automatic","created":1644920026,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"Hr8BlZNQzCa3_EUs2W8-SDB4wycRkhjH2_mpvkNKG7A"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}



When I press the back button from Stripe :



> {"id":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KTO2YDgVX1eRHhK3ZfdUdU6"},"client_secret":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6_secret_FFyJR50pcJHNf5H26hfzdfyOz","confirmation_method":"automatic","created":1644920026,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"Hr8BlZNQzCa3_EUs2W8-SDB4wycRkhjH2_mpvkNKG7A"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}

> {"id":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KTO2YDgVX1eRHhK3ZfdUdU6"},"client_secret":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6_secret_FFyJR50pcJHNf5H26hfzdfyOz","confirmation_method":"automatic","created":1644920026,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"Hr8BlZNQzCa3_EUs2W8-SDB4wycRkhjH2_mpvkNKG7A"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}

> {"id":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KTO2YDgVX1eRHhK3ZfdUdU6"},"client_secret":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6_secret_FFyJR50pcJHNf5H26hfzdfyOz","confirmation_method":"automatic","created":1644920026,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"Hr8BlZNQzCa3_EUs2W8-SDB4wycRkhjH2_mpvkNKG7A"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}

> {"id":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KTO2YDgVX1eRHhK3ZfdUdU6"},"client_secret":"pi_3KTO2YDgVX1eRHhK3ZfdUdU6_secret_FFyJR50pcJHNf5H26hfzdfyOz","confirmation_method":"automatic","created":1644920026,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":false,"metadata":{"token_hash":"Hr8BlZNQzCa3_EUs2W8-SDB4wycRkhjH2_mpvkNKG7A"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}

**Comment by Loocos** [comment]
I'm going to debug this on the prod env and will see the model result

**Comment by Prometee** [comment]
Since the STRIPE API is always giving json object with an `object` attribute, I don't think it's related to Stripe API version used.

According to your first stack trace I can see that the Webhook Stripe JSON data are well processed, then [`AbstractPaymentAction`](https://github.com/FLUX-SE/PayumStripe/blob/master/src/Action/Api/WebhookEvent/AbstractPaymentAction.php#L27-L34) is retrieving the `metadata` `token_hash` to retrieve the right Payum `Token` which contains the link to the Sylius `Payment`.
The Sylius `Payment` retrieved from the database seems to contains `details` with wrong data into it, making the `Sync` fail.

You can try to get the right `Payment` details and see if there is some weird things into it :

1. Get to the Stripe Webhook JSON request data having the issue
2. Search for `metadata` and copy the `token_hash` value
3. Query your prod database to search for this token :
```sql
SELECT * FROM sylius_payment_security_token WHERE has="1234567890abcdEF....";
```
4. inside the `details` column you will get a PHP serialized object which allows you to know what is the related Sylius `Payment`, example :
```
O:25:"Payum\Core\Model\Identity":2:{i:0;i:28930;i:1;s:35:"Sylius\Component\Core\Model\Payment";}
```
It's an Identify object with two attributes `id` and `class` the first attribute here is the integer with the value `28930`
5. With this integer get the related Sylius `Payment`
6. watch for the `details` column

**Comment by Loocos** [comment]
Hi @Prometee,

So I tried to debug on local and dev,  impossible to get the same error. I don't know why, even with a full synced db
This only happen in prod environment. Then I've added XDEBUG (in prod). Tried to debug, and magically, it never debug on the throw exception.
I realized this happen when u click on the "Pay" button from Sylius and get redirected to Stripe, so it can't debug because I think Stripe is sending request to our shop and then the error happen.

I'm a bit frustrated to not be able to provide you more information and also to cannot found a solution to this problem.

Now I'm going to see for the payment details like your comment above.

**Comment by Loocos** [comment]
Like you told me previously, the object attribute is present so all should be good ?
`{"id":"pi_3KVeI1DgVX1eRHhK1LF6vlzW","object":"payment_intent","amount":990,"amount_capturable":0,"amount_received":0,"application":null,"application_fee_amount":null,"automatic_payment_methods":null,"canceled_at":null,"cancellation_reason":null,"capture_method":"automatic","charges":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"\/v1\/charges?payment_intent=pi_3KVeI1DgVX1eRHhK1LF6vlzW"},"client_secret":"pi_3KVeI1DgVX1eRHhK1LF6vlzW_secret_RzcRj75piQkJb30yEopPo767C","confirmation_method":"automatic","created":1645459145,"currency":"eur","customer":null,"description":null,"invoice":null,"last_payment_error":null,"livemode":true,"metadata":{"token_hash":"ebaZfMrSrf_YKEKTonkqiryTz7BATmI28cVi_afKwpU"},"next_action":null,"on_behalf_of":null,"payment_method":null,"payment_method_options":{"card":{"installments":null,"network":null,"request_three_d_secure":"automatic"}},"payment_method_types":["card"],"processing":null,"receipt_email":null,"review":null,"setup_future_usage":null,"shipping":null,"source":null,"statement_descriptor":null,"statement_descriptor_suffix":null,"status":"requires_payment_method","transfer_data":null,"transfer_group":null}`

**Comment by Prometee** [comment]
@Loocos to see what really happen just before the error throw you can replace the original `SyncAction`, by creating a new one with a copy of the content like this :

```yaml
App\Payum\Stripe\SyncAction:
    public: true
    tags:
      - name: payum.action
        factory: stripe_checkout_session
        alias: app.payum.stripe.sync
        preprend: true
```

And modify the [line 42](https://github.com/FLUX-SE/PayumStripe/blob/master/src/Action/SyncAction.php#L42) with this :

```php
$modelAsJson = json_encode($model->getArrayCopy(), JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT);
throw new LogicException(sprintf('The synced object must have an "object" attribute ! Model given : %s', $modelAsJson));
```

**Comment by GSadee** [comment]
I'm closing this one as it should resolved.
