### ISSUE TITLE
AllSession ClassNotFoundError 

### ISSUE THREAD

**Issue by Loocos** [FLUX-SE/SyliusPayumStripePlugin#39]
Hi,

Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "AllSession" from namespace "FluxSE\PayumStripe\Request\Api\Resource".
Did you forget a "use" statement for another namespace?" at /app/vendor/flux-se/sylius-payum-stripe-plugin/src/Factory/AllSessionRequestFactory.php line 14

On payment/capture/{token}

Will send a PR when I get free time

**Comment by Loocos** [comment]
My version of `flux-se/payum-stripe` is v2.0.7, the latest release

**Comment by Prometee** [comment]
The latest is `v2.0.10` : https://packagist.org/packages/flux-se/payum-stripe

**Comment by Loocos** [comment]
Ok so, I've to required this one `flux-se/payum-stripe` in addition to this one `flux-se/sylius-payum-stripe-plugin` ?
But why it is not required directly from [SyliusPayumStripePlugin](https://github.com/FLUX-SE/SyliusPayumStripePlugin)
SyliusPayumStripePlugin ?

**Comment by Loocos** [comment]
Ok maybe I've missed something which doesn't update successfully this package (stripe php).
Will close it if solved, thanks for your answers.
