### ISSUE TITLE
How order paymentState is updated to state "authorized" ?

### ISSUE THREAD

**Issue by nfacciolo** [FLUX-SE/SyliusPayumStripePlugin#42]
Once the stripe payment is done, the payment state is updated just before the redirection but how ?

**Comment by Prometee** [comment]
Hello @nfacciolo 

Each Payum lib is handling this the same way.

First a [Payum Action](https://github.com/FLUX-SE/PayumStripe/blob/master/src/Action/StatusPaymentIntentAction.php)  is handling the change and then Payum is saving it to the database.
