### ISSUE TITLE
Is it possible to use connected account balances for payments with FLUX-SE/SyliusPayumStripePlugin?

### ISSUE THREAD

**Issue by PiotrSzymanski2000** [FLUX-SE/SyliusPayumStripePlugin#52]
Hello FLUX-SE/SyliusPayumStripePlugin maintainers,

I am currently using the FLUX-SE/SyliusPayumStripePlugin for a marketplace platform built on Sylius, and I am exploring the payment capabilities within our ecosystem.

We have a scenario where our vendors, each with their connected Stripe accounts, are interested in using their Stripe account balances to make purchases from other vendors within our marketplace. This feature would greatly enhance our marketplace functionality by allowing vendors to utilize their earnings for transactions within the platform.

Could you please provide information on whether the current implementation of FLUX-SE/SyliusPayumStripePlugin supports the use of Stripe connected account balances directly for payments?

We would appreciate any guidance on how to approach this functionality, including any necessary customizations or extensions that may be required to enable such a feature within the Sylius platform using your plugin.

Thank you for your time and support.

**Comment by Prometee** [comment]
Hello @PiotrSzymanski2000!

The way I build this Sylius Plugin it allows you to cover most of what Stripe offers including Stripe connect.
Depending on the scenario you can:

- https://stripe.com/docs/connect/creating-a-payments-page?destination-or-direct=destination-charges
- https://stripe.com/docs/connect/creating-a-payments-page?destination-or-direct=direct-charges
- https://stripe.com/docs/connect/creating-a-payments-page?destination-or-direct=separate-charges-transfers

The first one is very easy, it will just just need you to decorates `flux_se.sylius_payum_stripe.provider.details` service and add the two required additional fields:

```php
// ...

use Stripe\Checkout\Session;

// ...

public function getDetails(OrderInterface $order): array
{
    $details = $this->decoratedDetailsProvider->getDetails($order);
    
    if (Session::MODE_PAYMENT !== $details['mode']) {
        returne $details;
    }
    
    if (false === $this->orderStripeConnectProvider->supports($order)) {
        return $details;
    }

    $details['payment_intent_data'] = array_merge(
        $details['payment_intent_data'] ?? [],
        [
            'application_fee_amount' => $this->orderStripeConnectProvider->getApplicationFeeAmount($order),
            'transfer_data' =>[
                'destination' => $this->orderStripeConnectProvider->getDestinationStripeAccountId($order),
            ],
        ]
    );

    returne $details;
}
```

_Note: `OrderStripeConnectProvider` must be a service that you will create to handle Stripe Connect enrollment and decide what amount you keep in your pocket. You can also get more info reading the Stripe documentation I linked._

**Comment by PiotrSzymanski2000** [comment]
Hello @Prometee,

Thank you for your response. I appreciate the links and the guidance on setting up different Stripe Connect charge scenarios. However, my query is slightly different from the standard integration process that you've described.

We already have a working Stripe integration, and our margin and vendor funding process operates as you've outlined. The specific situation I'm referring to isn't covered in the Stripe documentation I've found. Let me elaborate: our platform is a marketplace with both vendors and buyers, where vendors have Stripe Connect accounts set up through the onboarding process. Currently, buyers can purchase products, and the payment goes to the vendor while we receive our commission.

The scenario in question is when a vendor wants to purchase from another vendor. Typically, this transaction requires the purchasing vendor to provide credit card details, and the payment is distributed accordingly. However, instead of this standard process, we are looking to see if a vendor can use the funds already available in their Stripe Connect account to make the purchase.

Since these funds are the proceeds from their sales and vendors have the option to withdraw them, we are wondering if there's a mechanism for them to use these funds directly for purchases within the marketplace, instead of withdrawing to a bank account.

Is there a way to facilitate such transactions using the available balance on a vendor's Stripe Connect account through the FLUX-SE/SyliusPayumStripePlugin?

**Comment by Prometee** [comment]
I know it's possible with PayPal since the account act like a real bank account, but Stripe is not made for this. However you can contact Stripe support to see if they have a way of handling this.

I can see, that there will be some issue with the amount available on each Stripe account since the fund are transferred each days to a real bank account.

At the end your needs are covered by the Stripe API library and this plugin is using it, so everything Stripe is providing can be used by this plugin.

**Comment by PiotrSzymanski2000** [comment]
Thank you very much for your prompt and detailed response. I greatly appreciate the time and effort you've invested in addressing my inquiry.
