### ISSUE TITLE
You cannot cancel this PaymentIntent because it has a status of canceled

### ISSUE THREAD

**Issue by bellu** [FLUX-SE/SyliusPayumStripePlugin#57]
I'm using the 2.0.9 version, and lately if a payment has been rejected from stripe or if i come back to the website without paying; i have this error on the website (see screenshot). 
Any suggestions?

<img width="1161" alt="Screenshot 2024-07-12 alle 15 50 37" src="https://github.com/user-attachments/assets/47d6817b-862f-46fd-8c12-681fe020adb0">

**Comment by Prometee** [comment]
Hello @bellu !

Are you able to update the plugin to v2.0.10 at least? It seems to be the same issue that already has been fixed.

**Comment by bellu** [comment]
Hi @Prometee!

I updated to the v2.0.10, but i've the same issue.
I saw here https://github.com/FLUX-SE/SyliusPayumStripePlugin/issues/53#issuecomment-2016904948 that you mention another workaround, can you be more specific please?

Thanks

**Comment by Prometee** [comment]
@bellu I already added this legacy action to the available one (https://github.com/FLUX-SE/PayumStripe/blob/master/src/StripeCheckoutSessionGatewayFactory.php#L43), then even if your Stripe API version is not a recent one it will execute it if needed.

Are you able to describe exactly what steps you are making to reproduce this error ? And do you have custom code running on this payment method ?

**Comment by bellu** [comment]
During the payment if i use the "back to the website" button on the stripe checkout page, i've this error.
I don't have any custom code for this payment method.

**Comment by Prometee** [comment]
`flux-se/sylius-payum-stripe-plugin`: at least 2.0.10 (Sylius plugin)
`flux-se/payum-stripe-bundle`: at least 2.0.1 (Symfony bundle)
`flux-se/payum-stripe`: at least 2.0.15 (basic payum lib)

The versions of those packages are not synced. but if you use this requirements in your `composer.json` :
```json
"require": {
    "flux-se/sylius-payum-stripe-plugin": "^2.0"
}
```
And you update the plugin then the rest will get updated with the latest version.

Unfortunately, I'm not able to reproduce your issue. When you come back from Stripe portal a Payum extension is taking care of expiring the Stripe Session :
https://github.com/FLUX-SE/SyliusPayumStripePlugin/blob/master/src/Extension/CancelExistingPaymentIntentExtension.php then the Payment is canceled and a new one is created by Sylius for the customer to retry with another payment ethod or the same one.
