### ISSUE TITLE
Error when calling GET /api/v2/shop/orders/{tokenValue}/payments/{paymentId}/configuration

### ISSUE THREAD

**Issue by ydemartino** [FLUX-SE/SyliusPayumStripePlugin#60]
Hello,

I have installed the plugin and enabled everything. 
The menu is correctly showing in the sylius admin panel and I have added Stripe JS with SCA support with the required keys.

Now when I try to call the  `GET /api/v2/shop/orders/{tokenValue}/payments/{paymentId}/configuration` 
I'm getting the following error:

```
request.CRITICAL: Uncaught PHP Exception Webmozart\Assert\InvalidArgumentException:
"Expected a value other than null." at /srv/app/vendor/webmozart/assert/src/Assert.php line 2074
{
  "exception":"[object] (Webmozart\\Assert\\InvalidArgumentException(code: 0):
                        Expected a value other than null.
                        at /srv/app/vendor/webmozart/assert/src/Assert.php:2074)"
} []
```

I don't have any other information, what am I missing for it to work?

Thank you

**Comment by Prometee** [comment]
Hi @ydemartino,

Do you call it with an existing `Order` with state `cart` ?
If you run it with `APP_ENV=dev` and `APP_DEBUG=1` you will also get the stack trace.

**Comment by ydemartino** [comment]
Hi, thanks for your quick reply!

I don't know Sylius well and was trying to pass the paymentMethodId, I didn't realize there was a payment object. Giving the correct paymentId for the token fixed it.
Thanks again!
